# Builder
FROM maven:3.8.7-eclipse-temurin-17 AS builder
WORKDIR /app
COPY Backend/pom.xml Backend/pom.xml
COPY Backend/src Backend/src
RUN mvn -f Backend/pom.xml -DskipTests package

# Runtime
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /app/Backend/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
