# Application
spring.application.name=thinwallet

<<<<<<< HEAD
# Perfil activo: "sql" usa MySQL/JPA | "mongo" usa MongoDB
# Para cambiar a NoSQL: cambiar a spring.profiles.active=mongo
spring.profiles.active=sql

=======
>>>>>>> cd492a2 (Guardando cambios antes del merge)
# Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://100.87.26.105:3306/thinwallet_db
spring.datasource.username=ThinWallet
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
<<<<<<< HEAD
<<<<<<< HEAD
logging.level.co.edu.unbosque=DEBUG

=======
logging.level.co.edu.unbosque=DEBUG
>>>>>>> 56605a3 (feat: implement features spec 002 (saldo) and 003 (transaction form) and fix styles)
# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ThinWalletTeam@gmail.com
spring.mail.password=xqhyysoxqfilsfpr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
<<<<<<< HEAD
=======
logging.level.co.edu.unbosque=DEBUG
>>>>>>> cd492a2 (Guardando cambios antes del merge)
=======

server.error.include-message=always
server.error.include-exception=true
>>>>>>> 56605a3 (feat: implement features spec 002 (saldo) and 003 (transaction form) and fix styles)
